
name: project_v1
description: Simple Kids Educational App.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.0
  flutter_svg: ^2.0.0
  flutter_tts: ^3.8.0
  animated_widgets: ^1.1.0
  audioplayers: ^5.0.0
  vibration: ^2.0.0
  platform: ^3.1.0
  win32: ^5.4.0
  lottie: ^2.7.0
  shared_preferences: ^2.3.2
  excel: ^2.1.0
  path_provider: ^2.1.4




dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  archive:
    path: third_party/archive
  
flutter_icons:
  image_path: "icons/logo.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/numbers/
    - assets/counters/
    - assets/animals/
    - assets/voices/
    - assets/voices/tts/
    - assets/letters/
    - assets/letters/avatars/
    - assets/letters/samples/
    - assets/family/
    - assets/games/memo/
    - assets/games/
    - assets/games/VegetablesetFruits/
    - assets/games/VegetablesetFruits/Fruits/
    - assets/games/VegetablesetFruits/Vegetables/
    - assets/games/puzzles/
    - assets/games/puzzles/1/
    - assets/games/puzzles/2/
    - assets/games/puzzles/3/
    - assets/games/puzzles/4/
    - assets/games/puzzles/5/
    - assets/games/puzzles/6/
    - assets/games/puzzles/7/
    - assets/games/puzzles/8/
    - assets/games/puzzles/9/
    - assets/games/puzzles/10/
    - assets/games/puzzles/11/
    - assets/games/puzzles/1/level_1_2x2/
    - assets/games/puzzles/1/level_2_3x3/
    - assets/games/puzzles/1/level_3_4x4/
    - assets/games/puzzles/2/level_1_2x2/
    - assets/games/puzzles/2/level_2_3x3/
    - assets/games/puzzles/2/level_3_4x4/
    - assets/games/puzzles/3/level_1_2x2/
    - assets/games/puzzles/3/level_2_3x3/
    - assets/games/puzzles/3/level_3_4x4/
    - assets/games/puzzles/4/level_1_2x2/
    - assets/games/puzzles/4/level_2_3x3/
    - assets/games/puzzles/4/level_3_4x4/
    - assets/games/puzzles/5/level_1_2x2/
    - assets/games/puzzles/5/level_2_3x3/
    - assets/games/puzzles/5/level_3_4x4/
    - assets/games/puzzles/6/level_1_2x2/
    - assets/games/puzzles/6/level_2_3x3/
    - assets/games/puzzles/6/level_3_4x4/
    - assets/games/puzzles/7/level_1_2x2/
    - assets/games/puzzles/7/level_2_3x3/
    - assets/games/puzzles/7/level_3_4x4/
    - assets/games/puzzles/8/level_1_2x2/
    - assets/games/puzzles/8/level_2_3x3/
    - assets/games/puzzles/8/level_3_4x4/
    - assets/games/puzzles/9/level_1_2x2/
    - assets/games/puzzles/9/level_2_3x3/
    - assets/games/puzzles/9/level_3_4x4/
    - assets/games/puzzles/10/level_1_2x2/
    - assets/games/puzzles/10/level_2_3x3/
    - assets/games/puzzles/10/level_3_4x4/
    - assets/games/puzzles/11/level_1_2x2/
    - assets/games/puzzles/11/level_2_3x3/
    - assets/games/puzzles/11/level_3_4x4/
    - assets/vegetables/
    - assets/fruits/
    - assets/json/
    - assets/cognitive/
    - assets/gamenumbers/
    - assets/gamenumbers/objects/
    - assets/gamenumbers/numbers/
    - assets/couleurs/
    - assets/emotions/



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
